from mongoengine import Document, StringField, DateTimeField, UUIDField, IntField, BooleanField, LongField

class Url(Document):
    id = UUIDField(primary_key=True)
    user_id = UUIDField(required=True)
    folder_id = UUIDField()
    domain_id = UUIDField()
    original_url = StringField(required=True)
    short_code = StringField(max_length=50, unique=True, required=True)
    custom_alias = StringField(max_length=255)
    title = StringField(max_length=255)
    description = StringField()
    qr_code_url = StringField()
    redirect_type = IntField(default=301)
    password_hash = StringField()
    click_count = LongField(default=0)
    unique_click_count = LongField(default=0)
    is_password_protected = BooleanField(default=False)
    is_guest_url = BooleanField(default=False)
    is_active = BooleanField(default=True)
    status = StringField(max_length=50, default='ACTIVE')
    expires_at = DateTimeField()
    created_at = DateTimeField()
    updated_at = DateTimeField()
